# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Moore Digital
email: john@johnmooredigital.com
description: > # this means to ignore newlines until "baseurl:"
  John Moore is a Digital Marketing expert based in Portland, Oregon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://johnmooredigital.com" # the base hostname & protocol for your site
twitter_username: jomoweb
github_username:  jomoweb

# Build settings
markdown: kramdown

# Sitemap Generator
gems:
  - jekyll-sitemap